# Generated by Django 5.2.11 on 2026-02-09 06:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('address', models.CharField(max_length=500, verbose_name='Адреса')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ціна (грн)')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='properties/', verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Об'єкт нерухомості",
                'verbose_name_plural': "Об'єкти нерухомості",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessibilityAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_access', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Доступність входу (1–10)')),
                ('entrance_status', models.CharField(blank=True, choices=[('inaccessible', 'Недоступно'), ('difficult', 'Важкодоступно'), ('needs_improvement', 'Потребує покращення'), ('ideal', 'Ідеально')], max_length=20, verbose_name='Статус входу')),
                ('entrance_comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар (вхід)')),
                ('lift_width_cm', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина ліфта (см)')),
                ('lift_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Бал ліфта (1–10)')),
                ('lift_comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар (ліфт)')),
                ('bathroom_type', models.CharField(blank=True, choices=[('bath', 'Ванна'), ('shower_tray', 'Душ з піддоном'), ('shower_drain', 'Душ-трап у підлогу')], max_length=20, verbose_name='Тип санвузлу')),
                ('bathroom_comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар (санвузол)')),
                ('thresholds_max_height_cm', models.FloatField(blank=True, null=True, verbose_name='Макс. висота порогів (см)')),
                ('thresholds_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Бал порогів (1–10)')),
                ('thresholds_comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар (пороги)')),
                ('turning_radius_exists', models.BooleanField(default=False, verbose_name='Наявність радіусу для розвороту')),
                ('turning_comment', models.CharField(blank=True, max_length=500, verbose_name='Коментар (розворот)')),
                ('total_score', models.FloatField(blank=True, null=True, verbose_name='Загальний бал')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='audit', to='properties.property', verbose_name="Об'єкт")),
            ],
            options={
                'verbose_name': 'Аудит доступності',
                'verbose_name_plural': 'Аудити доступності',
            },
        ),
    ]
