# Generated by Django 5.2.11 on 2026-02-09 08:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='area_sqm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Площа (м²)'),
        ),
        migrations.AddField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубліковано'),
        ),
        migrations.AddField(
            model_name='property',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Продаж'), ('rent', 'Оренда')], default='sale', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='property',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість кімнат'),
        ),
    ]
