# Generated by Django 5.2.11 on 2026-02-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_add_listing_type_rooms_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Зручність',
                'verbose_name_plural': 'Зручності',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='property',
            name='mobility_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = повна автономність, 2 = з помічником, 3 = базова', null=True, verbose_name='Рівень доступності (1–3)'),
        ),
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.ManyToManyField(blank=True, to='properties.feature', verbose_name='Зручності'),
        ),
    ]
