# Generated by Django 5.2.7 on 2026-02-26 08:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_features_mobility_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to=settings.AUTH_USER_MODEL, verbose_name='Власник оголошення'),
        ),
        migrations.AlterField(
            model_name='property',
            name='mobility_level',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1 = батьки з дитиною, 2 = без руки, 3 = крісло, 4 = без руки/ноги, 5 = універсальний', null=True, verbose_name='Рівень доступності (1–5)'),
        ),
    ]
