# Generated by Django 5.2.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_add_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Оголошення показується вище в каталозі.', verbose_name='Підвищена видимість (платне)'),
        ),
    ]
