# Generated by Django

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_add_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/%Y/%m/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_photos', to='properties.property', verbose_name='Оголошення')),
            ],
            options={
                'verbose_name': 'Фото оголошення',
                'verbose_name_plural': 'Фото оголошень',
                'ordering': ['order', 'id'],
            },
        ),
    ]
