# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_propertyphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='featured_until',
            field=models.DateTimeField(blank=True, help_text='До якої дати діє підвищена видимість.', null=True, verbose_name='Реклама до'),
        ),
        migrations.AddField(
            model_name='property',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Перегляди'),
        ),
        migrations.AddField(
            model_name='property',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Контактний телефон'),
        ),
        migrations.AddField(
            model_name='property',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Позначка, що нерухомість реальна (перевірено адміністрацією).', verbose_name='Перевірене оголошення'),
        ),
    ]
