# Generated by Django 5.2.7 on 2026-04-26 21:26

from django.db import migrations
from django.utils.text import slugify
import uuid

LUN_RIA_FEATURES = [
    'Автономне опалення',
    'Центральне опалення',
    'Газ',
    'Бойлер',
    'Кондиціонер',
    'Пральна машина',
    'Посудомийна машина',
    'Холодильник',
    'Мікрохвильова піч',
    'Духова шафа',
    'Меблі на кухні',
    'Ванна',
    'Душова кабіна',
    'Wi-Fi',
    'Телевізор',
    'Балкон / Лоджія',
    'Панорамні вікна',
    'Ліфт',
    'Вантажний ліфт',
    'Консьєрж',
    'Охорона території',
    'Відеоспостереження',
    'Підземний паркінг',
    'Гостьовий паркінг',
    'Є генератор / резервне живлення',
    'Можна з тваринами',
    'Можна з дітьми',
]

def update_features(apps, schema_editor):
    Feature = apps.get_model('properties', 'Feature')
    Feature.objects.all().delete()
    
    for name in LUN_RIA_FEATURES:
        slug = slugify(name, allow_unicode=True)
        if not slug:
            slug = str(uuid.uuid4())[:8]
        
        original_slug = slug
        counter = 1
        while Feature.objects.filter(slug=slug).exists():
            slug = f"{original_slug}-{counter}"
            counter += 1
            
        Feature.objects.create(name=name, slug=slug)

def reverse_features(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_profilereview'),
    ]

    operations = [
        migrations.RunPython(update_features, reverse_features),
    ]
