# Generated by Django 5.2.7 on 2026-04-26 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_add_lun_ria_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='category',
            field=models.CharField(choices=[('apartment', 'В квартирі'), ('building', 'В будинку та на території'), ('rules', 'Правила проживання')], default='apartment', max_length=20, verbose_name='Категорія'),
        ),
    ]
