# Generated by Django 5.2.7 on 2026-04-26 21:30

from django.db import migrations

def assign_categories(apps, schema_editor):
    Feature = apps.get_model('properties', 'Feature')
    
    # Categorization
    categories = {
        'apartment': [
            'Автономне опалення', 'Центральне опалення', 'Газ', 'Бойлер', 
            'Кондиціонер', 'Пральна машина', 'Посудомийна машина', 'Холодильник', 
            'Мікрохвильова піч', 'Духова шафа', 'Меблі на кухні', 'Ванна', 
            'Душова кабіна', 'Wi-Fi', 'Телевізор', 'Балкон / Лоджія', 'Панорамні вікна'
        ],
        'building': [
            'Ліфт', 'Вантажний ліфт', 'Консьєрж', 'Охорона території', 
            'Відеоспостереження', 'Підземний паркінг', 'Гостьовий паркінг', 
            'Є генератор / резервне живлення'
        ],
        'rules': [
            'Можна з тваринами', 'Можна з дітьми'
        ]
    }
    
    for category, names in categories.items():
        Feature.objects.filter(name__in=names).update(category=category)

def reverse_categories(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_add_feature_category'),
    ]

    operations = [
        migrations.RunPython(assign_categories, reverse_categories),
    ]
